### PR TITLE
Better management of Unused input

### PR DESCRIPTION
**Pull request by zclod**
This is a "rewrite" inspired by your work with the goal of manage correctly unused input from the Get monad. 
This is accomplished with the Data.Machine.Stack module.

the actual behaviour is to discard unused input of the current chunk of data

```
run $ source ["abc", "d", "efgh"] ~> streamGet (getByteString 2)
> [Right "ab", Right "de"]
```

with this pull request you get the expected behaviour

```
run $ source ["abc", "d", "efgh"] ~> streamGet (getByteString 2)
> [Right "ab",Right "cd",Right "ef",Right "gh"]
```

---
Also added nix support

### CODE REVIEW

**Comment by aloiscochard** [comment]
This looks fantastic, thanks @zclod ... also I'm a nix user and I feel like I'll learn a few things by reading the `*.nix` stuff.

I'll try to review it over the weekend, cheers!

**Comment by zclod** [comment]
Great

For the nix stuff I'm learning too, check out this great tutorial about nix and haskell
[nix tutorial](https://github.com/Gabriel439/haskell-nix) if you haven't alredy

**Comment by zclod** [comment]
any chance to get this merged?

**Comment by aloiscochard** [comment]
@zclod so sorry, totally got out of my mind I'm afraid.

It is now merged, do you want me to cut a release?

**Comment by aloiscochard** [comment]
Thanks for the nix stuff, very appreciated :)

**Comment by zclod** [comment]
No problem :)
I think a release could be a good idea since there is new documentation

**Pull request merged**
